services:
  agenda-api:
    build:
      context: ./BLUE - AgendaAPI
      dockerfile: Dockerfile
    container_name: agenda-container
    ports:
      - "8080:8080"
    environment:
      - STR_CONEXAO=${STR_CONEXAO}
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - agenda-network
    restart: unless-stopped

  agenda-web:
    build:
      context: ./BLUE - AgendaWEB
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: agendaweb-frontend
    ports:
      - "3000:80"
    depends_on:
      - agenda-api
    networks:
      - agenda-network
    restart: unless-stopped

networks:
  agenda-network:
    driver: bridge